#!/bin/bash
#SBATCH -A ac5616p
#SBATCH --partition=GPU-AI
#SBATCH --nodes=1
#SBATCH --gres=gpu:volta16:1
#SBATCH --time=1:00:00
#SBATCH --mail-user=brianleepollack@gmail.com
#SBATCH --output={str(self.logdir)}/job_n{number}.stdout
#SBATCH --error={str(self.logdir)}/job_n{number}.stderr

set -x
echo "$@"
source /pghbio/dbmi/batmanlab/bpollack/anaconda3/etc/profile.d/conda.sh
conda activate new_mre
