#!/bin/bash
#SBATCH -A ac5616p
#SBATCH --partition=GPU-AI
#SBATCH --nodes=1
#SBATCH --gres=gpu:volta16:1
#SBATCH --time=1:00:00
#SBATCH --mail-user=brianleepollack@gmail.com
#SBATCH --output=/pylon5/ac5616p/bpollack/mre_slurm/2019-05-24_17-15-50/job_n0.stdout
