#!/bin/bash
#SBATCH -A ac5616p
#SBATCH --partition=GPU-AI
#SBATCH --nodes=1
#SBATCH --gres=gpu:volta16:1
#SBATCH --time=1:00:00
#SBATCH --mail-user=brianleepollack@gmail.com
#SBATCH --output=/pylon5/ac5616p/bpollack/mre_slurm/2019-05-24_17-15-59/job_n0.stdout
#SBATCH --error=/pylon5/ac5616p/bpollack/mre_slurm/2019-05-24_17-15-59/job_n0.stderr

set -x
echo "$@"
source /pghbio/dbmi/batmanlab/bpollack/anaconda3/etc/profile.d/conda.sh
conda activate new_mre
